[2025-04-08T23:42:45.386Z] [ERROR] Error storing intent in database {"message":"Table 'sas2.ai_intents' doesn't exist","stack":"Error: Table 'sas2.ai_intents' doesn't exist\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\db.js:17:45)\n    at recognizeIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\utils\\intentRecognition.js:201:14)\n    at testIntentRecognition (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\test.js:18:26)\n    at Object.<anonymous> (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\test.js:24:1)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)"}
[2025-04-08T23:42:45.392Z] [ERROR] Error storing intent in database {"message":"Table 'sas2.ai_intents' doesn't exist","stack":"Error: Table 'sas2.ai_intents' doesn't exist\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\db.js:17:45)\n    at recognizeIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\utils\\intentRecognition.js:201:14)\n    at testIntentRecognition (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\test.js:18:26)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-08T23:42:45.396Z] [ERROR] Error storing intent in database {"message":"Table 'sas2.ai_intents' doesn't exist","stack":"Error: Table 'sas2.ai_intents' doesn't exist\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\db.js:17:45)\n    at recognizeIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\utils\\intentRecognition.js:201:14)\n    at testIntentRecognition (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\test.js:18:26)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-08T23:42:45.401Z] [ERROR] Error storing intent in database {"message":"Table 'sas2.ai_intents' doesn't exist","stack":"Error: Table 'sas2.ai_intents' doesn't exist\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\db.js:17:45)\n    at recognizeIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\utils\\intentRecognition.js:201:14)\n    at testIntentRecognition (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\test.js:18:26)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-08T23:42:45.409Z] [ERROR] Error storing intent in database {"message":"Table 'sas2.ai_intents' doesn't exist","stack":"Error: Table 'sas2.ai_intents' doesn't exist\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\db.js:17:45)\n    at recognizeIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\utils\\intentRecognition.js:201:14)\n    at testIntentRecognition (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\test.js:18:26)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-08T23:42:45.415Z] [ERROR] Error storing intent in database {"message":"Table 'sas2.ai_intents' doesn't exist","stack":"Error: Table 'sas2.ai_intents' doesn't exist\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\db.js:17:45)\n    at recognizeIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\utils\\intentRecognition.js:201:14)\n    at testIntentRecognition (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\test.js:18:26)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-08T23:51:36.369Z] [ERROR] Error storing intent in database {"message":"Table 'sas2.ai_intents' doesn't exist","stack":"Error: Table 'sas2.ai_intents' doesn't exist\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\db.js:17:45)\n    at recognizeIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\utils\\intentRecognition.js:201:14)\n    at testIntentRecognition (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\test.js:18:26)\n    at Object.<anonymous> (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\test.js:24:1)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)"}
[2025-04-08T23:51:36.375Z] [ERROR] Error storing intent in database {"message":"Table 'sas2.ai_intents' doesn't exist","stack":"Error: Table 'sas2.ai_intents' doesn't exist\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\db.js:17:45)\n    at recognizeIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\utils\\intentRecognition.js:201:14)\n    at testIntentRecognition (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\test.js:18:26)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-08T23:51:36.380Z] [ERROR] Error storing intent in database {"message":"Table 'sas2.ai_intents' doesn't exist","stack":"Error: Table 'sas2.ai_intents' doesn't exist\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\db.js:17:45)\n    at recognizeIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\utils\\intentRecognition.js:201:14)\n    at testIntentRecognition (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\test.js:18:26)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-08T23:51:36.386Z] [ERROR] Error storing intent in database {"message":"Table 'sas2.ai_intents' doesn't exist","stack":"Error: Table 'sas2.ai_intents' doesn't exist\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\db.js:17:45)\n    at recognizeIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\utils\\intentRecognition.js:201:14)\n    at testIntentRecognition (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\test.js:18:26)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-08T23:51:36.397Z] [ERROR] Error storing intent in database {"message":"Table 'sas2.ai_intents' doesn't exist","stack":"Error: Table 'sas2.ai_intents' doesn't exist\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\db.js:17:45)\n    at recognizeIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\utils\\intentRecognition.js:201:14)\n    at testIntentRecognition (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\test.js:18:26)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-08T23:51:36.402Z] [ERROR] Error storing intent in database {"message":"Table 'sas2.ai_intents' doesn't exist","stack":"Error: Table 'sas2.ai_intents' doesn't exist\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\db.js:17:45)\n    at recognizeIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\utils\\intentRecognition.js:201:14)\n    at testIntentRecognition (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\test.js:18:26)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-08T23:52:41.230Z] [ERROR] Error storing intent in database {"message":"Table 'sas2.ai_intents' doesn't exist","stack":"Error: Table 'sas2.ai_intents' doesn't exist\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\db.js:17:45)\n    at recognizeIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\utils\\intentRecognition.js:201:14)\n    at testIntentRecognition (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\test.js:18:26)\n    at Object.<anonymous> (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\test.js:24:1)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)"}
[2025-04-08T23:52:41.236Z] [ERROR] Error storing intent in database {"message":"Table 'sas2.ai_intents' doesn't exist","stack":"Error: Table 'sas2.ai_intents' doesn't exist\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\db.js:17:45)\n    at recognizeIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\utils\\intentRecognition.js:201:14)\n    at testIntentRecognition (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\test.js:18:26)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-08T23:52:41.241Z] [ERROR] Error storing intent in database {"message":"Table 'sas2.ai_intents' doesn't exist","stack":"Error: Table 'sas2.ai_intents' doesn't exist\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\db.js:17:45)\n    at recognizeIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\utils\\intentRecognition.js:201:14)\n    at testIntentRecognition (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\test.js:18:26)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-08T23:52:41.246Z] [ERROR] Error storing intent in database {"message":"Table 'sas2.ai_intents' doesn't exist","stack":"Error: Table 'sas2.ai_intents' doesn't exist\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\db.js:17:45)\n    at recognizeIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\utils\\intentRecognition.js:201:14)\n    at testIntentRecognition (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\test.js:18:26)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-08T23:52:41.254Z] [ERROR] Error storing intent in database {"message":"Table 'sas2.ai_intents' doesn't exist","stack":"Error: Table 'sas2.ai_intents' doesn't exist\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\db.js:17:45)\n    at recognizeIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\utils\\intentRecognition.js:201:14)\n    at testIntentRecognition (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\test.js:18:26)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-08T23:52:41.265Z] [ERROR] Error storing intent in database {"message":"Table 'sas2.ai_intents' doesn't exist","stack":"Error: Table 'sas2.ai_intents' doesn't exist\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\db.js:17:45)\n    at recognizeIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\utils\\intentRecognition.js:201:14)\n    at testIntentRecognition (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\test.js:18:26)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-09T16:55:55.590Z] [ERROR] Error connecting to the database: {"message":"Access denied for user 'root'@'localhost' (using password: NO)","stack":"Error: Access denied for user 'root'@'localhost' (using password: NO)\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at testConnection (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\server.js:35:31)\n    at Object.<anonymous> (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\server.js:42:1)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)"}
[2025-04-09T17:00:09.254Z] [ERROR] Error connecting to the database: {"message":"Access denied for user 'root'@'localhost' (using password: NO)","stack":"Error: Access denied for user 'root'@'localhost' (using password: NO)\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at testConnection (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\server.js:35:31)\n    at Object.<anonymous> (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\server.js:42:1)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)"}
[2025-04-09T17:20:15.744Z] [ERROR] Error storing user message in chat history {"message":"Table 'sas2.user_chat_history' doesn't exist","stack":"Error: Table 'sas2.user_chat_history' doesn't exist\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\db.js:17:45)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\routes\\ai.routes.js:216:16\n    at Layer.handleRequest (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\router\\lib\\layer.js:152:17)\n    at next (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\router\\lib\\route.js:157:13)\n    at devAuthMiddleware (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\middleware\\dev.middleware.js:16:3)\n    at Layer.handleRequest (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\router\\lib\\layer.js:152:17)\n    at next (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\router\\lib\\route.js:157:13)\n    at Route.dispatch (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\router\\lib\\route.js:117:3)\n    at handle (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\router\\index.js:435:11)"}
[2025-04-09T17:20:15.748Z] [ERROR] Error storing intent in database {"message":"Table 'sas2.ai_intents' doesn't exist","stack":"Error: Table 'sas2.ai_intents' doesn't exist\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\db.js:17:45)\n    at recognizeIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\utils\\intentRecognition.js:320:14)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\routes\\ai.routes.js:226:26\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-09T17:20:15.764Z] [ERROR] Error storing AI response in chat history {"message":"Table 'sas2.user_chat_history' doesn't exist","stack":"Error: Table 'sas2.user_chat_history' doesn't exist\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\db.js:17:45)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\routes\\ai.routes.js:233:16\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-09T17:20:30.270Z] [ERROR] Error storing user message in chat history {"message":"Table 'sas2.user_chat_history' doesn't exist","stack":"Error: Table 'sas2.user_chat_history' doesn't exist\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\db.js:17:45)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\routes\\ai.routes.js:216:16\n    at Layer.handleRequest (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\router\\lib\\layer.js:152:17)\n    at next (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\router\\lib\\route.js:157:13)\n    at devAuthMiddleware (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\middleware\\dev.middleware.js:16:3)\n    at Layer.handleRequest (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\router\\lib\\layer.js:152:17)\n    at next (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\router\\lib\\route.js:157:13)\n    at Route.dispatch (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\router\\lib\\route.js:117:3)\n    at handle (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\router\\index.js:435:11)"}
[2025-04-09T17:20:30.276Z] [ERROR] Error storing intent in database {"message":"Table 'sas2.ai_intents' doesn't exist","stack":"Error: Table 'sas2.ai_intents' doesn't exist\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\db.js:17:45)\n    at recognizeIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\utils\\intentRecognition.js:320:14)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\routes\\ai.routes.js:226:26\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-09T17:20:42.174Z] [ERROR] Error logging AI interaction {"message":"Cannot add or update a child row: a foreign key constraint fails (`sas2`.`ai_interaction_logs`, CONSTRAINT `ai_interaction_logs_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE)","stack":"Error: Cannot add or update a child row: a foreign key constraint fails (`sas2`.`ai_interaction_logs`, CONSTRAINT `ai_interaction_logs_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE)\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\db.js:17:45)\n    at callDeepseekAPI (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\utils\\intentHandlers.js:43:16)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async handleGeneralAdvice (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\utils\\intentHandlers.js:738:24)\n    at async handleIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\utils\\intentHandlers.js:1122:16)\n    at async C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\routes\\ai.routes.js:229:22"}
[2025-04-09T17:20:42.204Z] [ERROR] Error storing AI response in chat history {"message":"Table 'sas2.user_chat_history' doesn't exist","stack":"Error: Table 'sas2.user_chat_history' doesn't exist\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\db.js:17:45)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\routes\\ai.routes.js:233:16\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-09T17:21:30.920Z] [ERROR] Error storing user message in chat history {"message":"Table 'sas2.user_chat_history' doesn't exist","stack":"Error: Table 'sas2.user_chat_history' doesn't exist\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\db.js:17:45)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\routes\\ai.routes.js:216:16\n    at Layer.handleRequest (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\router\\lib\\layer.js:152:17)\n    at next (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\router\\lib\\route.js:157:13)\n    at devAuthMiddleware (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\middleware\\dev.middleware.js:16:3)\n    at Layer.handleRequest (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\router\\lib\\layer.js:152:17)\n    at next (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\router\\lib\\route.js:157:13)\n    at Route.dispatch (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\router\\lib\\route.js:117:3)\n    at handle (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\router\\index.js:435:11)"}
[2025-04-09T17:21:30.925Z] [ERROR] Error storing intent in database {"message":"Table 'sas2.ai_intents' doesn't exist","stack":"Error: Table 'sas2.ai_intents' doesn't exist\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\db.js:17:45)\n    at recognizeIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\utils\\intentRecognition.js:320:14)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\routes\\ai.routes.js:226:26\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-09T17:21:44.567Z] [ERROR] Error logging AI interaction {"message":"Cannot add or update a child row: a foreign key constraint fails (`sas2`.`ai_interaction_logs`, CONSTRAINT `ai_interaction_logs_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE)","stack":"Error: Cannot add or update a child row: a foreign key constraint fails (`sas2`.`ai_interaction_logs`, CONSTRAINT `ai_interaction_logs_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE)\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\db.js:17:45)\n    at callDeepseekAPI (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\utils\\intentHandlers.js:43:16)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async handleGeneralAdvice (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\utils\\intentHandlers.js:738:24)\n    at async handleIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\utils\\intentHandlers.js:1122:16)\n    at async C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\routes\\ai.routes.js:229:22"}
[2025-04-09T17:21:44.601Z] [ERROR] Error storing AI response in chat history {"message":"Table 'sas2.user_chat_history' doesn't exist","stack":"Error: Table 'sas2.user_chat_history' doesn't exist\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\db.js:17:45)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\routes\\ai.routes.js:233:16\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-09T17:41:19.457Z] [ERROR] Error storing user message in chat history {"message":"Table 'sas2.user_chat_history' doesn't exist","stack":"Error: Table 'sas2.user_chat_history' doesn't exist\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\db.js:17:45)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\routes\\ai.routes.js:216:16\n    at Layer.handleRequest (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\router\\lib\\layer.js:152:17)\n    at next (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\router\\lib\\route.js:157:13)\n    at devAuthMiddleware (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\middleware\\dev.middleware.js:16:3)\n    at Layer.handleRequest (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\router\\lib\\layer.js:152:17)\n    at next (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\router\\lib\\route.js:157:13)\n    at Route.dispatch (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\router\\lib\\route.js:117:3)\n    at handle (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\router\\index.js:435:11)"}
[2025-04-09T17:41:19.463Z] [ERROR] Error storing intent in database {"message":"Table 'sas2.ai_intents' doesn't exist","stack":"Error: Table 'sas2.ai_intents' doesn't exist\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\db.js:17:45)\n    at recognizeIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\utils\\intentRecognition.js:320:14)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\routes\\ai.routes.js:226:26\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-09T17:41:19.467Z] [ERROR] Error storing AI response in chat history {"message":"Table 'sas2.user_chat_history' doesn't exist","stack":"Error: Table 'sas2.user_chat_history' doesn't exist\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\db.js:17:45)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\routes\\ai.routes.js:233:16\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-09T17:41:28.450Z] [ERROR] Error storing user message in chat history {"message":"Table 'sas2.user_chat_history' doesn't exist","stack":"Error: Table 'sas2.user_chat_history' doesn't exist\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\db.js:17:45)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\routes\\ai.routes.js:216:16\n    at Layer.handleRequest (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\router\\lib\\layer.js:152:17)\n    at next (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\router\\lib\\route.js:157:13)\n    at devAuthMiddleware (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\middleware\\dev.middleware.js:16:3)\n    at Layer.handleRequest (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\router\\lib\\layer.js:152:17)\n    at next (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\router\\lib\\route.js:157:13)\n    at Route.dispatch (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\router\\lib\\route.js:117:3)\n    at handle (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\router\\index.js:435:11)"}
[2025-04-09T17:41:28.454Z] [ERROR] Error storing intent in database {"message":"Table 'sas2.ai_intents' doesn't exist","stack":"Error: Table 'sas2.ai_intents' doesn't exist\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\db.js:17:45)\n    at recognizeIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\utils\\intentRecognition.js:320:14)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\routes\\ai.routes.js:226:26\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-09T17:41:42.741Z] [ERROR] Error logging AI interaction {"message":"Cannot add or update a child row: a foreign key constraint fails (`sas2`.`ai_interaction_logs`, CONSTRAINT `ai_interaction_logs_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE)","stack":"Error: Cannot add or update a child row: a foreign key constraint fails (`sas2`.`ai_interaction_logs`, CONSTRAINT `ai_interaction_logs_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE)\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\db.js:17:45)\n    at callDeepseekAPI (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\utils\\intentHandlers.js:43:16)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async handleGeneralAdvice (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\utils\\intentHandlers.js:738:24)\n    at async handleIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\utils\\intentHandlers.js:1122:16)\n    at async C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\routes\\ai.routes.js:229:22"}
[2025-04-09T17:41:42.749Z] [ERROR] Error storing AI response in chat history {"message":"Table 'sas2.user_chat_history' doesn't exist","stack":"Error: Table 'sas2.user_chat_history' doesn't exist\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\db.js:17:45)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\routes\\ai.routes.js:233:16\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-09T17:42:19.625Z] [ERROR] Error storing user message in chat history {"message":"Table 'sas2.user_chat_history' doesn't exist","stack":"Error: Table 'sas2.user_chat_history' doesn't exist\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\db.js:17:45)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\routes\\ai.routes.js:216:16\n    at Layer.handleRequest (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\router\\lib\\layer.js:152:17)\n    at next (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\router\\lib\\route.js:157:13)\n    at devAuthMiddleware (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\middleware\\dev.middleware.js:16:3)\n    at Layer.handleRequest (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\router\\lib\\layer.js:152:17)\n    at next (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\router\\lib\\route.js:157:13)\n    at Route.dispatch (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\router\\lib\\route.js:117:3)\n    at handle (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\router\\index.js:435:11)"}
[2025-04-09T17:42:19.631Z] [ERROR] Error storing intent in database {"message":"Table 'sas2.ai_intents' doesn't exist","stack":"Error: Table 'sas2.ai_intents' doesn't exist\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\db.js:17:45)\n    at recognizeIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\utils\\intentRecognition.js:320:14)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\routes\\ai.routes.js:226:26\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-09T17:42:29.452Z] [ERROR] Error logging AI interaction {"message":"Cannot add or update a child row: a foreign key constraint fails (`sas2`.`ai_interaction_logs`, CONSTRAINT `ai_interaction_logs_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE)","stack":"Error: Cannot add or update a child row: a foreign key constraint fails (`sas2`.`ai_interaction_logs`, CONSTRAINT `ai_interaction_logs_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE)\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\db.js:17:45)\n    at callDeepseekAPI (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\utils\\intentHandlers.js:43:16)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async handleGeneralAdvice (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\utils\\intentHandlers.js:738:24)\n    at async handleIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\utils\\intentHandlers.js:1122:16)\n    at async C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\routes\\ai.routes.js:229:22"}
[2025-04-09T17:42:29.488Z] [ERROR] Error storing AI response in chat history {"message":"Table 'sas2.user_chat_history' doesn't exist","stack":"Error: Table 'sas2.user_chat_history' doesn't exist\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\db.js:17:45)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\routes\\ai.routes.js:233:16\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-09T18:18:01.369Z] [ERROR] Error connecting to the database: {"message":"Access denied for user 'root'@'localhost' (using password: NO)","stack":"Error: Access denied for user 'root'@'localhost' (using password: NO)\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at testConnection (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\server.js:35:31)\n    at Object.<anonymous> (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\server.js:42:1)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)"}
[2025-04-09T18:30:43.564Z] [ERROR] Error connecting to the database: {"message":"Access denied for user 'root'@'localhost' (using password: NO)","stack":"Error: Access denied for user 'root'@'localhost' (using password: NO)\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at testConnection (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\server.js:36:16)\n    at Object.<anonymous> (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\server.js:78:1)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)"}
[2025-04-09T18:31:16.899Z] [ERROR] Error connecting to the database: {"message":"Access denied for user 'root'@'localhost' (using password: NO)","stack":"Error: Access denied for user 'root'@'localhost' (using password: NO)\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at testConnection (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\server.js:36:16)\n    at Object.<anonymous> (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\server.js:78:1)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)"}
[2025-04-09T18:57:57.974Z] [ERROR] Error connecting to the database: {"message":"Access denied for user 'root'@'localhost' (using password: NO)","stack":"Error: Access denied for user 'root'@'localhost' (using password: NO)\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at testConnection (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\server.js:36:16)\n    at Object.<anonymous> (C:\\Users\\usuario1\\Desktop\\SAS 2\\SASBACK\\server.js:78:1)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)"}
[2025-04-09T19:12:24.814Z] [ERROR] Error connecting to the database: {"message":"Access denied for user 'root'@'localhost' (using password: NO)","stack":"Error: Access denied for user 'root'@'localhost' (using password: NO)\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at testConnection (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\server.js:36:16)\n    at Object.<anonymous> (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\server.js:78:1)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)"}
[2025-04-09T19:17:20.905Z] [ERROR] Error connecting to the database: {"message":"Access denied for user 'root'@'localhost' (using password: NO)","stack":"Error: Access denied for user 'root'@'localhost' (using password: NO)\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at testConnection (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\server.js:36:16)\n    at Object.<anonymous> (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\server.js:78:1)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)"}
[2025-04-09T19:20:31.520Z] [ERROR] Error connecting to the database: {"message":"Access denied for user 'root'@'localhost' (using password: NO)","stack":"Error: Access denied for user 'root'@'localhost' (using password: NO)\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at testConnection (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\server.js:36:16)\n    at Object.<anonymous> (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\server.js:78:1)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)"}
[2025-04-09T19:21:02.618Z] [ERROR] Error storing user message in chat history {"message":"Access denied for user 'root'@'localhost' (using password: NO)","stack":"Error: Access denied for user 'root'@'localhost' (using password: NO)\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\db.js:25:45)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\routes\\ai.routes.js:216:16\n    at Layer.handleRequest (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\lib\\layer.js:152:17)\n    at next (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\lib\\route.js:157:13)\n    at devAuthMiddleware (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\middleware\\dev.middleware.js:16:3)\n    at Layer.handleRequest (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\lib\\layer.js:152:17)\n    at next (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\lib\\route.js:157:13)\n    at Route.dispatch (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\lib\\route.js:117:3)\n    at handle (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\index.js:435:11)"}
[2025-04-09T19:21:02.653Z] [ERROR] Error storing intent in database {"message":"Access denied for user 'root'@'localhost' (using password: NO)","stack":"Error: Access denied for user 'root'@'localhost' (using password: NO)\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\db.js:25:45)\n    at recognizeIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\utils\\intentRecognition.js:451:14)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\routes\\ai.routes.js:226:26\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-09T19:21:02.671Z] [ERROR] Error getting user name from database {"message":"Access denied for user 'root'@'localhost' (using password: NO)","stack":"Error: Access denied for user 'root'@'localhost' (using password: NO)\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\db.js:25:45)\n    at handleGreeting (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\utils\\intentHandlers.js:1280:35)\n    at handleIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\utils\\intentHandlers.js:1375:22)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\routes\\ai.routes.js:229:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-09T19:21:02.686Z] [ERROR] Error storing AI response in chat history {"message":"Access denied for user 'root'@'localhost' (using password: NO)","stack":"Error: Access denied for user 'root'@'localhost' (using password: NO)\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\db.js:25:45)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\routes\\ai.routes.js:233:16\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-09T19:24:34.341Z] [ERROR] Error storing user message in chat history {"message":"Access denied for user 'root'@'localhost' (using password: NO)","stack":"Error: Access denied for user 'root'@'localhost' (using password: NO)\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\db.js:25:45)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\routes\\ai.routes.js:216:16\n    at Layer.handleRequest (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\lib\\layer.js:152:17)\n    at next (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\lib\\route.js:157:13)\n    at devAuthMiddleware (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\middleware\\dev.middleware.js:16:3)\n    at Layer.handleRequest (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\lib\\layer.js:152:17)\n    at next (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\lib\\route.js:157:13)\n    at Route.dispatch (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\lib\\route.js:117:3)\n    at handle (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\index.js:435:11)"}
[2025-04-09T19:24:34.358Z] [ERROR] Error storing intent in database {"message":"Access denied for user 'root'@'localhost' (using password: NO)","stack":"Error: Access denied for user 'root'@'localhost' (using password: NO)\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\db.js:25:45)\n    at recognizeIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\utils\\intentRecognition.js:451:14)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\routes\\ai.routes.js:226:26\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-09T19:24:34.370Z] [ERROR] Error getting user name from database {"message":"Access denied for user 'root'@'localhost' (using password: NO)","stack":"Error: Access denied for user 'root'@'localhost' (using password: NO)\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\db.js:25:45)\n    at handleGreeting (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\utils\\intentHandlers.js:1280:35)\n    at handleIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\utils\\intentHandlers.js:1375:22)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\routes\\ai.routes.js:229:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-09T19:24:34.379Z] [ERROR] Error storing AI response in chat history {"message":"Access denied for user 'root'@'localhost' (using password: NO)","stack":"Error: Access denied for user 'root'@'localhost' (using password: NO)\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\db.js:25:45)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\routes\\ai.routes.js:233:16\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-09T19:28:22.765Z] [ERROR] Error connecting to the database: {"message":"Access denied for user 'root'@'localhost' (using password: NO)","stack":"Error: Access denied for user 'root'@'localhost' (using password: NO)\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at testConnection (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\server.js:36:16)\n    at Object.<anonymous> (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\server.js:78:1)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)"}
[2025-04-09T19:29:51.421Z] [ERROR] Error storing user message in chat history {"message":"Access denied for user 'root'@'localhost' (using password: NO)","stack":"Error: Access denied for user 'root'@'localhost' (using password: NO)\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\db.js:25:45)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\routes\\ai.routes.js:217:16\n    at Layer.handleRequest (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\lib\\layer.js:152:17)\n    at next (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\lib\\route.js:157:13)\n    at devAuthMiddleware (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\middleware\\dev.middleware.js:16:3)\n    at Layer.handleRequest (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\lib\\layer.js:152:17)\n    at next (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\lib\\route.js:157:13)\n    at Route.dispatch (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\lib\\route.js:117:3)\n    at handle (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\index.js:435:11)"}
[2025-04-09T19:29:51.436Z] [ERROR] Error storing intent in database {"message":"Access denied for user 'root'@'localhost' (using password: NO)","stack":"Error: Access denied for user 'root'@'localhost' (using password: NO)\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\db.js:25:45)\n    at recognizeIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\utils\\intentRecognition.js:451:14)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\routes\\ai.routes.js:227:26\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-09T19:29:51.444Z] [ERROR] Error processing chat message: {"message":"handleIntent is not a function","stack":"TypeError: handleIntent is not a function\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\routes\\ai.routes.js:230:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-09T19:41:31.245Z] [ERROR] Error connecting to the database: {"message":"Access denied for user 'root'@'localhost' (using password: NO)","stack":"Error: Access denied for user 'root'@'localhost' (using password: NO)\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at testConnection (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\server.js:36:16)\n    at Object.<anonymous> (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\server.js:78:1)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)"}
[2025-04-09T19:42:15.925Z] [ERROR] Error storing user message in chat history {"message":"Access denied for user 'root'@'localhost' (using password: NO)","stack":"Error: Access denied for user 'root'@'localhost' (using password: NO)\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\db.js:25:45)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\routes\\ai.routes.js:217:16\n    at Layer.handleRequest (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\lib\\layer.js:152:17)\n    at next (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\lib\\route.js:157:13)\n    at devAuthMiddleware (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\middleware\\dev.middleware.js:16:3)\n    at Layer.handleRequest (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\lib\\layer.js:152:17)\n    at next (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\lib\\route.js:157:13)\n    at Route.dispatch (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\lib\\route.js:117:3)\n    at handle (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\index.js:435:11)"}
[2025-04-09T19:42:15.984Z] [ERROR] Error storing intent in database {"message":"Access denied for user 'root'@'localhost' (using password: NO)","stack":"Error: Access denied for user 'root'@'localhost' (using password: NO)\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\db.js:25:45)\n    at recognizeIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\utils\\intentRecognition.js:451:14)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\routes\\ai.routes.js:227:26\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-09T19:42:15.987Z] [ERROR] Error processing chat message: {"message":"handleIntent is not a function","stack":"TypeError: handleIntent is not a function\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\routes\\ai.routes.js:230:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-09T19:46:17.139Z] [ERROR] Error connecting to the database: {"message":"Access denied for user 'root'@'localhost' (using password: NO)","stack":"Error: Access denied for user 'root'@'localhost' (using password: NO)\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at testConnection (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\server.js:36:16)\n    at Object.<anonymous> (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\server.js:78:1)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)"}
[2025-04-09T19:48:24.315Z] [ERROR] Error connecting to the database: {"message":"Access denied for user 'root'@'localhost' (using password: NO)","stack":"Error: Access denied for user 'root'@'localhost' (using password: NO)\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at testConnection (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\server.js:36:16)\n    at Object.<anonymous> (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\server.js:78:1)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)"}
[2025-04-09T19:52:08.071Z] [ERROR] Error connecting to the database: {"message":"Access denied for user 'root'@'localhost' (using password: NO)","stack":"Error: Access denied for user 'root'@'localhost' (using password: NO)\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at testConnection (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\server.js:36:16)\n    at Object.<anonymous> (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\server.js:78:1)\n    at Module._compile (node:internal/modules/cjs/loader:1554:14)\n    at Object..js (node:internal/modules/cjs/loader:1706:10)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)"}
[2025-04-09T19:54:05.894Z] [ERROR] Error storing user message in chat history {"message":"Access denied for user 'root'@'localhost' (using password: NO)","stack":"Error: Access denied for user 'root'@'localhost' (using password: NO)\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\db.js:25:45)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\routes\\ai.routes.js:217:16\n    at Layer.handleRequest (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\lib\\layer.js:152:17)\n    at next (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\lib\\route.js:157:13)\n    at devAuthMiddleware (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\middleware\\dev.middleware.js:16:3)\n    at Layer.handleRequest (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\lib\\layer.js:152:17)\n    at next (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\lib\\route.js:157:13)\n    at Route.dispatch (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\lib\\route.js:117:3)\n    at handle (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\index.js:435:11)"}
[2025-04-09T19:54:05.907Z] [ERROR] Error storing intent in database {"message":"Access denied for user 'root'@'localhost' (using password: NO)","stack":"Error: Access denied for user 'root'@'localhost' (using password: NO)\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\db.js:25:45)\n    at recognizeIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\utils\\intentRecognition.js:451:14)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\routes\\ai.routes.js:227:26\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-09T19:54:05.918Z] [ERROR] Error getting user name from database {"message":"Access denied for user 'root'@'localhost' (using password: NO)","stack":"Error: Access denied for user 'root'@'localhost' (using password: NO)\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\db.js:25:45)\n    at handleGreeting (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\utils\\intentHandlers.js:1429:35)\n    at handleIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\utils\\intentHandlers.js:1524:22)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\routes\\ai.routes.js:230:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-09T19:54:05.926Z] [ERROR] Error storing AI response in chat history {"message":"Access denied for user 'root'@'localhost' (using password: NO)","stack":"Error: Access denied for user 'root'@'localhost' (using password: NO)\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\db.js:25:45)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\routes\\ai.routes.js:234:16\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-09T19:55:02.057Z] [ERROR] Error storing user message in chat history {"message":"Access denied for user 'root'@'localhost' (using password: NO)","stack":"Error: Access denied for user 'root'@'localhost' (using password: NO)\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\db.js:25:45)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\routes\\ai.routes.js:217:16\n    at Layer.handleRequest (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\lib\\layer.js:152:17)\n    at next (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\lib\\route.js:157:13)\n    at devAuthMiddleware (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\middleware\\dev.middleware.js:16:3)\n    at Layer.handleRequest (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\lib\\layer.js:152:17)\n    at next (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\lib\\route.js:157:13)\n    at Route.dispatch (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\lib\\route.js:117:3)\n    at handle (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\index.js:435:11)"}
[2025-04-09T19:55:02.071Z] [ERROR] Error storing intent in database {"message":"Access denied for user 'root'@'localhost' (using password: NO)","stack":"Error: Access denied for user 'root'@'localhost' (using password: NO)\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\db.js:25:45)\n    at recognizeIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\utils\\intentRecognition.js:451:14)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\routes\\ai.routes.js:227:26\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-09T19:55:27.553Z] [ERROR] Error logging AI interaction {"message":"Access denied for user 'root'@'localhost' (using password: NO)","stack":"Error: Access denied for user 'root'@'localhost' (using password: NO)\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\db.js:25:45)\n    at callDeepseekAPI (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\utils\\intentHandlers.js:43:16)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async handleGeneralAdvice (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\utils\\intentHandlers.js:1129:24)\n    at async handleIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\utils\\intentHandlers.js:1529:16)\n    at async C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\routes\\ai.routes.js:230:22"}
[2025-04-09T19:55:27.804Z] [ERROR] Error processing structured data {"message":"Access denied for user 'root'@'localhost' (using password: NO)","stack":"Error: Access denied for user 'root'@'localhost' (using password: NO)\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\db.js:25:45)\n    at processStructuredData (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\utils\\intentHandlers.js:892:33)\n    at handleGeneralAdvice (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\utils\\intentHandlers.js:1137:29)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async handleIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\utils\\intentHandlers.js:1529:16)\n    at async C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\routes\\ai.routes.js:230:22"}
[2025-04-09T19:55:27.816Z] [ERROR] Error storing AI response in chat history {"message":"Access denied for user 'root'@'localhost' (using password: NO)","stack":"Error: Access denied for user 'root'@'localhost' (using password: NO)\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\db.js:25:45)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\routes\\ai.routes.js:234:16\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-09T20:01:58.100Z] [ERROR] Error storing user message in chat history {"message":"No database selected","stack":"Error: No database selected\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\db.js:25:45)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\routes\\ai.routes.js:217:16\n    at Layer.handleRequest (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\lib\\layer.js:152:17)\n    at next (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\lib\\route.js:157:13)\n    at devAuthMiddleware (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\middleware\\dev.middleware.js:16:3)\n    at Layer.handleRequest (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\lib\\layer.js:152:17)\n    at next (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\lib\\route.js:157:13)\n    at Route.dispatch (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\lib\\route.js:117:3)\n    at handle (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\index.js:435:11)"}
[2025-04-09T20:01:58.112Z] [ERROR] Error storing intent in database {"message":"No database selected","stack":"Error: No database selected\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\db.js:25:45)\n    at recognizeIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\utils\\intentRecognition.js:451:14)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\routes\\ai.routes.js:227:26\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-09T20:01:58.126Z] [ERROR] Error getting user name from database {"message":"No database selected","stack":"Error: No database selected\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\db.js:25:45)\n    at handleGreeting (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\utils\\intentHandlers.js:1429:35)\n    at handleIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\utils\\intentHandlers.js:1524:22)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\routes\\ai.routes.js:230:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-09T20:01:58.144Z] [ERROR] Error storing AI response in chat history {"message":"No database selected","stack":"Error: No database selected\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\db.js:25:45)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\routes\\ai.routes.js:234:16\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-09T20:02:26.271Z] [ERROR] Error storing user message in chat history {"message":"No database selected","stack":"Error: No database selected\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\db.js:25:45)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\routes\\ai.routes.js:217:16\n    at Layer.handleRequest (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\lib\\layer.js:152:17)\n    at next (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\lib\\route.js:157:13)\n    at devAuthMiddleware (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\middleware\\dev.middleware.js:16:3)\n    at Layer.handleRequest (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\lib\\layer.js:152:17)\n    at next (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\lib\\route.js:157:13)\n    at Route.dispatch (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\lib\\route.js:117:3)\n    at handle (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\router\\index.js:435:11)"}
[2025-04-09T20:02:26.283Z] [ERROR] Error storing intent in database {"message":"No database selected","stack":"Error: No database selected\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\db.js:25:45)\n    at recognizeIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\utils\\intentRecognition.js:451:14)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\routes\\ai.routes.js:227:26\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
[2025-04-09T20:02:57.835Z] [ERROR] Error logging AI interaction {"message":"No database selected","stack":"Error: No database selected\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\db.js:25:45)\n    at callDeepseekAPI (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\utils\\intentHandlers.js:43:16)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async handleGeneralAdvice (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\utils\\intentHandlers.js:1129:24)\n    at async handleIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\utils\\intentHandlers.js:1529:16)\n    at async C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\routes\\ai.routes.js:230:22"}
[2025-04-09T20:02:58.028Z] [ERROR] Error processing structured data {"message":"No database selected","stack":"Error: No database selected\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\db.js:25:45)\n    at processStructuredData (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\utils\\intentHandlers.js:892:33)\n    at handleGeneralAdvice (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\utils\\intentHandlers.js:1137:29)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async handleIntent (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\utils\\intentHandlers.js:1529:16)\n    at async C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\routes\\ai.routes.js:230:22"}
[2025-04-09T20:02:58.039Z] [ERROR] Error storing AI response in chat history {"message":"No database selected","stack":"Error: No database selected\n    at PromisePool.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\node_modules\\mysql2\\lib\\promise\\pool.js:36:22)\n    at Object.query (C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\db.js:25:45)\n    at C:\\Users\\usuario1\\Desktop\\SAS 2\\sas_fitness\\SASBACK\\routes\\ai.routes.js:234:16\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"}
